[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
board_build.partitions = partitions.csv
board_build.filesystem = littlefs
extra_scripts = post:scripts/merge_firmware.py
lib_deps =
    marcoschwartz/LiquidCrystal_I2C@^1.1.4
    bblanchon/ArduinoJson@6.21.5
monitor_speed = 115200
